# docker-compose-dev.yml

services:
  app:
    image: ags_integration_hub_image:latest
    container_name: ags_integration_hub
    build:
      context: ..
      dockerfile: ags_deployment/Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    volumes:
      - ../:/app
    ports:
      - "8790:8790"
    command: python3 /app/run.py
    networks:
      - custom_network
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    ports:
      - "8791:8791"
    depends_on:
      - app
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge